AWSTemplateFormatVersion: 2010-09-09
Description: 'Microservice deploy for pn-delayer'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic

  WebApiDnsName:
    Type: String
    Description: 'The DNS name used for WEB rest API.'
  
  CorsAllowedDomains:
    Type: String
    Description: 'Comma separated list of domains allowed to make cross origin request'

  ContainerImageUri:
    Type: String
    Description: 'Exact container image URI with full repository and image digest'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  ECSClusterName:
    Type: String
    Description: 'The name of the ECS cluster where the microservice is going to be deployed'

  SubnetsIds:
    Type: String
    Description: 'subnets ids comma separated list. Where to deploy the microservice'

  VpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'
  
  EcsDefaultSecurityGroup:
    Type: String
    Description: 'Default security group required by infrastructure'

  ApplicationLoadBalancerListenerArn:
    Type: String
    Description: 'Load balancer listener where HTTP endpoints is going to be registered'

  ApplicationLoadBalancerDomain:
    Type: String
    Description: 'Base URL of the load balancer where the service is going to be reachable'

  NetworkLoadBalancerLink:
    Type: String
    Description: 'network load balancer link for API-GW'
  
  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Kinesis stream that receive logs'
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  PaperDeliveryDriverCapacitiesTableName:
    Type: String
    Description: 'DynamoDB table name for PaperDeliveryDriverCapacities'

  PaperDeliveryDriverCapacitiesTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing PaperDeliveryDriverCapacities'

  PaperDeliveryDriverCapacitiesDispatchedTableName:
    Type: String
    Description: 'DynamoDB table name for  PaperDeliveryDriverCapacitiesDispatched'

  PaperDeliveryDriverCapacitiesDispatchedTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing  PaperDeliveryDriverCapacitiesDispatched'

  PaperDeliveryHighPriorityTableName:
    Type: String
    Description: 'DynamoDB table name for PaperDeliveryHighPriority'

  PaperDeliveryHighPriorityTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing PaperDeliveryHighPriority'

  PaperDeliveryReadyToSendTableName:
    Type: String
    Description: 'DynamoDB table name for PaperDeliveryReadyToSend'

  PaperDeliveryReadyToSendTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing PaperDeliveryReadyToSend'

  HighPriorityQueryLimit:
    Type: Number
    Description: 'Max elements quantity for high priority query'


Resources:

  # pn-delayer microservice
  DelayerMicroservice:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-delayer'
        CpuValue: 512
        MemoryAmount: 2GB
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        ContainerImageURI: !Sub '${ContainerImageUri}'
        ContainerEnvEntry1: !Sub 'AWS_REGIONCODE=${AWS::Region}'
        ContainerEnvEntry2: !Sub 'PN_DELAYER_DAO_PAPERDELIVERYDRIVERCAPACITIESTABLENAME=${PaperDeliveryDriverCapacitiesTableName}'
        ContainerEnvEntry3: !Sub 'PN_DELAYER_DAO_PAPERDELIVERYDRIVERCAPACITIESDISPATCHEDTABLENAME=${PaperDeliveryDriverCapacitiesDispatchedTableName}'
        ContainerEnvEntry4: !Sub 'PN_DELAYER_DAO_PAPERDELIVERYHIGHPRIORITYTABLENAME=${PaperDeliveryHighPriorityTableName}'
        ContainerEnvEntry5: !Sub 'PN_DELAYER_DAO_PAPERDELIVERYREAYTOSENDTABLENAME=${PaperDeliveryReadyToSendTableName}'
        ContainerEnvEntry6: !Sub 'PN_DELAYER_HIGHPRIORITYQUERYLIMIT =${HighPriorityQueryLimit}'
        MappedPaths: '/delayer/*'
        ECSClusterName: !Ref ECSClusterName
        Subnets: !Ref SubnetsIds
        VpcId: !Ref VpcId
        EcsDefaultSecurityGroup: !Ref EcsDefaultSecurityGroup
        LoadBalancerListenerArn: !Ref ApplicationLoadBalancerListenerArn
        LoadbalancerRulePriority: !Ref MicroserviceNumber
        CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn

  # Grant operational rights to pn-Delayer microservice
  DelayerMicroserviceTaskManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:BatchGetItem
            Resource:
              - !Sub "${PaperDeliveryDriverCapacitiesDispatchedTableArn}"
              - !Sub "${PaperDeliveryDriverCapacitiesDispatchedTableArn}/*"
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
            Resource:
              - !Sub "${PaperDeliveryDriverCapacitiesTableArn}"
              - !Sub "${PaperDeliveryDriverCapacitiesTableArn}/*"
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:Query
              - dynamodb:TransactWriteItems
            Resource:
              - !Sub "${PaperDeliveryHighPriorityTableArn}"
              - !Sub "${PaperDeliveryHighPriorityTableArn}/*"
              - !Sub "${PaperDeliveryReadyToSendTableArn}"
              - !Sub "${PaperDeliveryReadyToSendTableArn}/*"




