AWSTemplateFormatVersion: 2010-09-09
Description: 'Microservice deploy for pn-delayer'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic

  WebApiDnsName:
    Type: String
    Description: 'The DNS name used for WEB rest API.'
  
  CorsAllowedDomains:
    Type: String
    Description: 'Comma separated list of domains allowed to make cross origin request'

  ContainerImageUri:
    Type: String
    Description: 'Exact container image URI with full repository and image digest'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  ECSClusterName:
    Type: String
    Description: 'The name of the ECS cluster where the microservice is going to be deployed'

  SubnetsIds:
    Type: String
    Description: 'subnets ids comma separated list. Where to deploy the microservice'

  VpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'
  
  EcsDefaultSecurityGroup:
    Type: String
    Description: 'Default security group required by infrastructure'

  ApplicationLoadBalancerListenerArn:
    Type: String
    Description: 'Load balancer listener where HTTP endpoints is going to be registered'

  ApplicationLoadBalancerDomain:
    Type: String
    Description: 'Base URL of the load balancer where the service is going to be reachable'

  NetworkLoadBalancerLink:
    Type: String
    Description: 'network load balancer link for API-GW'
  
  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Kinesis stream that receive logs'
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  PaperDeliveryDriverCapacitiesTableName:
    Type: String
    Description: 'DynamoDB table name for PaperDeliveryDriverCapacities'

  PaperDeliveryDriverCapacitiesTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing PaperDeliveryDriverCapacities'

  PaperDeliveryDriverUsedCapacitiesTableName:
    Type: String
    Description: 'DynamoDB table name for  PaperDeliveryDriverUsedCapacities'

  PaperDeliveryDriverUsedCapacitiesTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing  PaperDeliveryDriverUsedCapacities'

  PaperDeliveryHighPriorityTableName:
    Type: String
    Description: 'DynamoDB table name for PaperDeliveryHighPriority'

  PaperDeliveryHighPriorityTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing PaperDeliveryHighPriority'

  PaperDeliveryReadyToSendTableName:
    Type: String
    Description: 'DynamoDB table name for PaperDeliveryReadyToSend'

  PaperDeliveryReadyToSendTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing PaperDeliveryReadyToSend'

  HighPriorityQueryLimit:
    Type: Number
    Description: 'Max elements quantity for high priority query'

  DeliveryDateDayOfWeek:
    Type: Number
    Description: 'Day of the week for capacity (0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday)'
    Default: 1

  DeliveryDateInterval:
    Type: String
    Description: 'Interval for deliveryDate setting'
    Default: 1d

  VpcCidr:
    Type: String
    Description: 'VPC Cidr default'

  # Log group parameters
  BatchLogGroup:
    Type: String
    Description: 'Batch log group name'

  MaxvCpus:
    Type: String
    Default: 128
    Description: The maximum number of Amazon EC2 vCPUs that an environment can reach.

  VCPU:
    Type: String
    Default: 0.25
    Description: The number of vCPUs reserved for the container.

  ComputeResourceType:
    Type: String
    Default: FARGATE
    AllowedValues:
      - FARGATE_SPOT
      - FARGATE
    Description: Enter FARGATE_SPOT or FARGATE.

  Memory:
    Type: String
    Default: 2048
    Description: The memory hard limit (in MiB) present to the container.

Resources:

  ## Compute Environment
  ComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ServiceRole: !Ref BatchServiceRole
      ComputeEnvironmentName: !Sub '${ProjectName}-delayer-compute-environment'
      ComputeResources:
        MaxvCpus: !Ref MaxvCpus
        Type: !Ref ComputeResourceType
        SecurityGroupIds: #Dubbio su chi può raggiungere il batch 
          - !Ref BatchSecurityGroup
        Subnets: !Split [",", !Ref SubnetsIds]
      State: ENABLED

  BatchProcessingJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      PropagateTags: true
      JobDefinitionName: !Sub '${ProjectName}-delayer-job-definition'
      ContainerProperties:
        Image: !Ref ContainerImageUri
        FargatePlatformConfiguration:
          PlatformVersion: LATEST
        ResourceRequirements:
          - Value: !Ref VCPU
            Type: VCPU
          - Value: !Ref Memory
            Type: MEMORY
        JobRoleArn: !GetAtt "BatchTaskExecutionRole.Arn"
        ExecutionRoleArn: !GetAtt "BatchTaskExecutionRole.Arn"
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref "BatchLogGroup"
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: !Sub '${ProjectName}-delayer-logs'
      PlatformCapabilities:
        - FARGATE
      Tags:
        Service: Batch
        Name: JobDefinitionTag
        Expected: MergeTag

  ## JobQueue
  JobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref ComputeEnvironment
      State: ENABLED
      Priority: 1
      JobQueueName: !Sub '${ProjectName}-delayer-job-queue'

  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  BatchTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-delayer-taskexec-role'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ecs-tasks.amazonaws.com ]
            Action: [ "sts:AssumeRole" ]
      Path: /
      ManagedPolicyArns:
        - !Ref DelayerMicroserviceTaskManagedPolicy
    
  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Batch Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: !Ref VpcCidr
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: "0.0.0.0/0"

  # Grant operational rights to pn-Delayer microservice
  DelayerMicroserviceTaskManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:BatchGetItem
            Resource:
              - !Sub "${PaperDeliveryDriverUsedCapacitiesTableArn}"
              - !Sub "${PaperDeliveryDriverUsedCapacitiesTableArn}/*"
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
            Resource:
              - !Sub "${PaperDeliveryDriverCapacitiesTableArn}"
              - !Sub "${PaperDeliveryDriverCapacitiesTableArn}/*"
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:Query
              - dynamodb:TransactWriteItems
            Resource:
              - !Sub "${PaperDeliveryHighPriorityTableArn}"
              - !Sub "${PaperDeliveryHighPriorityTableArn}/*"
              - !Sub "${PaperDeliveryReadyToSendTableArn}"
              - !Sub "${PaperDeliveryReadyToSendTableArn}/*"

  DelayerMicroserviceCloudWatchDashboard:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/microservice-cloudwatch-dashboard.yaml"
      Parameters:
        DashboardName: !Sub "${ProjectName}-delayer"
        DynamoDBTableNames: !Join
          - ','
          - - !Ref PaperDeliveryDriverCapacitiesTableName
            - !Ref PaperDeliveryDriverUsedCapacitiesTableName
            - !Ref PaperDeliveryHighPriorityTableName
            - !Ref PaperDeliveryReadyToSendTableName
        LogGroupsNames: !Join
          - ','
          - - !Sub '/aws/ecs/${ProjectName}-delayer'




