AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  PnDelayerInputsRetentionHours:
    Type: Number
    Default: 168
    Description: Number of hours to retain data records in the stream

  PnDelayerInputsStandardAlarmThresholdsMs:
    Type: Number
    Default: 2000000
    Description: Threshold for standard alarms in milliseconds

  PnDelayerInputsOnCallAlarmThresholdsMs:
    Type: Number
    Default: 2000000
    Description: Threshold for oncall alarms in milliseconds 

  AlarmSNSTopicArn:
    Type: String
    
  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

  LogRetention:
    Type: Number
    Default: 14

  AlarmSNSTopicName:
    Type: String
    Description: "Topic alarm"

Resources:
  # PaperDeliveryDriverCapacities DynamoDB Table
  PaperDeliveryDriverCapacitiesTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliveryDriverCapacities'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "activationDateFrom"
          AttributeType: "S"
        - AttributeName: "tenderIdGeoKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "activationDateFrom"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "tenderIdGeoKey-index"
          KeySchema:
            - AttributeName: "tenderIdGeoKey"
              KeyType: "HASH"
            - AttributeName: "activationDateFrom"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PaperDeliveryDriverUsedCapacitiesTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliveryDriverUsedCapacities'
      AttributeDefinitions:
        - AttributeName: "unifiedDeliveryDriverGeokey"
          AttributeType: "S"
        - AttributeName: "deliveryDate"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "unifiedDeliveryDriverGeokey"
          KeyType: "HASH"
        - AttributeName: "deliveryDate"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "deliveryDate-index"
          KeySchema:
            - AttributeName: "deliveryDate"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PaperDeliveryKinesisEventTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliveryKinesisEvent'
      AttributeDefinitions:
        - AttributeName: "requestId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "requestId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PaperDeliverySenderLimitTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliverySenderLimit'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "deliveryDate"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "deliveryDate"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PaperDeliveryUsedSenderLimitTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliveryUsedSenderLimit'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "deliveryDate"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "deliveryDate"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  ProvinceTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperChannelProvince'
      AttributeDefinitions:
        - AttributeName: "region"
          AttributeType: "S"
        - AttributeName: "province"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "region"
          KeyType: "HASH"
        - AttributeName: "province"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PaperDeliveryCounterTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliveryCounters'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PaperDeliveryTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-DelayerPaperDelivery'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "S"
        - AttributeName: "requestId"
          AttributeType: "S"
        - AttributeName: "createdAt"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "requestId-CreatedAt-index"
          KeySchema:
            - AttributeName: "requestId"
              KeyType: "HASH"
            - AttributeName: "createdAt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  ### Kinesis Data Stream: kinesis data stream for pn-delayer-inputs
  PnDelayerInputsKinesisDataStream:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-data-stream.yaml"
      Parameters:
        StreamName: "pn-delayer_inputs"
        # PROVISIONED MODE: follow shard configuration
        StreamRetentionHours: !Ref PnDelayerInputsRetentionHours
        RequireManagedKey: true
        # USES SNSTopic used for all Kinesis alarms
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        StandardAlarmThresholdsMs: !Ref PnDelayerInputsStandardAlarmThresholdsMs
        OnCallAlarmThresholdsMs: !Ref PnDelayerInputsOnCallAlarmThresholdsMs

  ### Communication FROM SafeStorage TO delayerReceiverOrdersSendersLambda ###
  SafeStorageToDelayerReceiverOrdersSendersLambdaQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-safestorage_to_delayer_orders_senders'
        DelaySeconds: 1
        VisibilityTimeout: 240 # 4 minutes
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        
  PnDelayerSenderLimitJobLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-delayer-sender-limit-job'
        LogGroupRetention: !Ref LogRetention
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn

  PnDelayerDriverCapacityJobLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-delayer-driver-capacity-job'
        LogGroupRetention: !Ref LogRetention
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn

  PnDelayerResidualCapacityJobLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-delayer-residual-capacity-job'
        LogGroupRetention: !Ref LogRetention
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn


  KinesisPaperDeliveryLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-delayer-kinesisPaperDeliveryLambda"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

  # internal queues DLQ
  KinesisPaperDeliveryLambdaDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delayer_kinesis_paper_delivery_DLQ'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicArn
        HasDLQ: "false"
        QueueHasAlarm: "true"

  DelayerToPaperChannelLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub ${TemplateBucketBaseUrl}/fragments/log-group.yaml
      Parameters:
        LogGroupName: !Sub ${ProjectName}-delayerToPaperChannelLambda
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: /aws/lambda

  TestDelayerLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub ${TemplateBucketBaseUrl}/fragments/log-group.yaml
      Parameters:
        LogGroupName: !Sub ${ProjectName}-testDelayerLambda
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: /aws/lambda

  DelayerReceiverOrdersSendersLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub ${TemplateBucketBaseUrl}/fragments/log-group.yaml
      Parameters:
        LogGroupName: !Sub ${ProjectName}-delayer-receiverOrdersSendersLambda
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: /aws/lambda

  TestDelayerKmsBucket:
    Type: AWS::KMS::Key
    Properties:
      Description: "Symmetric Encryption KMS for TestDelayer's Buckets"
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable Permissions on all user and roles
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  TestDelayerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-${ProjectName}-test-delayer-bucket"
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !GetAtt TestDelayerKmsBucket.Arn

Outputs:
  # Dynamo tables
  PaperDeliveryDriverCapacitiesTableName:
    Description: Name of dynamodb table containing capacities
    Value: !Ref PaperDeliveryDriverCapacitiesTable
  PaperDeliveryDriverCapacitiesTableArn:
    Description: ARN of dynamodb table containing capacities
    Value: !Sub '${PaperDeliveryDriverCapacitiesTable.Arn}'

  PaperDeliveryDriverUsedCapacitiesTableName:
    Description: Name of dynamodb table containing used capacities
    Value: !Ref PaperDeliveryDriverUsedCapacitiesTable
  PaperDeliveryDriverUsedCapacitiesTableArn:
    Description: ARN of dynamodb table containing used capacities
    Value: !Sub '${PaperDeliveryDriverUsedCapacitiesTable.Arn}'

  PaperDeliveryKinesisEventTableName:
    Description: Name of dynamodb table containing Kinesis sequenceNumber for paper deliveries
    Value: !Ref PaperDeliveryKinesisEventTable
  PaperDeliveryKinesisEventTableArn:
    Description: ARN of dynamodb table containing Kinesis sequenceNumber for paper deliveries
    Value: !Sub '${PaperDeliveryKinesisEventTable.Arn}'

  PaperDeliveryTableName:
    Description: Name of dynamodb table containing paper deliveries workflow
    Value: !Ref PaperDeliveryTable
  PaperDeliveryTableArn:
    Description: ARN of dynamodb table containing paper deliveries workflow
    Value: !Sub '${PaperDeliveryTable.Arn}'
  PaperDeliveryTableStreamArn:
    Description: ARN of dynamodb table stream containing paper deliveries workflow
    Value: !GetAtt PaperDeliveryTable.StreamArn

  PaperDeliveryCounterTableName:
    Description: Name of dynamodb table containing PaperDeliveryCounter
    Value: !Ref PaperDeliveryCounterTable
  PaperDeliveryCounterTableArn:
    Description: ARN of dynamodb table containing PaperDeliveryCounter
    Value: !Sub '${PaperDeliveryCounterTable.Arn}'

  PaperDeliverySenderLimitTableName:
    Description: Name of dynamodb table containing PaperDeliverySenderLimit
    Value: !Ref PaperDeliverySenderLimitTable
  PaperDeliverySenderLimitTableArn:
    Description: ARN of dynamodb table containing PaperDeliverySenderLimit
    Value: !Sub '${PaperDeliverySenderLimitTable.Arn}'

  PaperDeliveryUsedSenderLimitTableName:
    Description: Name of dynamodb table containing PaperDeliveryUsedSenderLimit
    Value: !Ref PaperDeliveryUsedSenderLimitTable
  PaperDeliveryUsedSenderLimitTableArn:
    Description: ARN of dynamodb table containing PaperDeliveryUsedSenderLimit
    Value: !Sub '${PaperDeliveryUsedSenderLimitTable.Arn}'

  ProvinceTableName:
    Description: Name of dynamodb table containing Province
    Value: !Ref ProvinceTable
  ProvinceTableArn:
    Description: ARN of dynamodb table containing Province
    Value: !Sub '${ProvinceTable.Arn}'

  # SQS
  SafeStorageToDelayerReceiverOrdersSendersLambdaQueueQueueName:
    Value: !GetAtt SafeStorageToDelayerReceiverOrdersSendersLambdaQueue.Outputs.QueueName
    Description: SafeStorage-to-delayerReceiverOrdersSendersLambda queue name
  SafeStorageToDelayerReceiverOrdersSendersLambdaQueueURL:
    Value: !GetAtt SafeStorageToDelayerReceiverOrdersSendersLambdaQueue.Outputs.QueueURL
    Description: SafeStorage-to-delayerReceiverOrdersSendersLambda queue URL
  SafeStorageToDelayerReceiverOrdersSendersLambdaQueueARN:
    Value: !GetAtt SafeStorageToDelayerReceiverOrdersSendersLambdaQueue.Outputs.QueueARN
    Description: SafeStorage-to-delayerReceiverOrdersSendersLambda queue ARN

  # Kinesis data stream
  PnDelayerInputsKinesisDataStreamArn:
    Value: !GetAtt PnDelayerInputsKinesisDataStream.Outputs.KinesisStreamArn
    Description: "PnDelayerInputs Kinesis source stream ARN"

  PnDelayerInputsKinesisDataStreamKMSArn:
    Value: !GetAtt PnDelayerInputsKinesisDataStream.Outputs.KinesisStreamKeyArn
    Description: "PnDelayerInputs Kinesis stream KMS ARN"

  # Log groups
  SenderLimitJobLogGroup:
    Value: !GetAtt PnDelayerSenderLimitJobLogGroup.Outputs.LogGroupName

  DriverCapacityJobLogGroup:
    Value: !GetAtt PnDelayerDriverCapacityJobLogGroup.Outputs.LogGroupName

  ResidualCapacityJobLogGroup:
    Value: !GetAtt PnDelayerResidualCapacityJobLogGroup.Outputs.LogGroupName

  # Lambda names
  KinesisPaperDeliveryLambdaName:
    Value: !Sub "${ProjectName}-delayer-kinesisPaperDeliveryLambda"

  DelayerToPaperChannelLambdaName:
    Value: !Sub "${ProjectName}-delayerToPaperChannelLambda"

  TestDelayerLambdaName:
    Value: !Sub "${ProjectName}-testDelayerLambda"

  DelayerReceiverOrdersSendersLambdaName:
    Value: !Sub "${ProjectName}-delayer-receiverOrdersSendersLambda"

  ExportDelayerDataLambdaName:
    Value: !Sub "${ProjectName}-exportDelayerData"

  KinesisPaperDeliveryLambdaDLQARN:
    Value: !GetAtt KinesisPaperDeliveryLambdaDLQ.Outputs.QueueARN
    Description: pn-delayer_kinesis_paper_delivery_DLQ' queue ARN

  # Buckets
  TestDelayerBucketName:
    Description: Name of bucket for delayer tests automation
    Value: !Ref TestDelayerBucket
  TestDelayerBucketArn:
    Description: Arn of bucket for delayer tests automation
    Value: !Sub '${TestDelayerBucket.Arn}'
  TestDelayerKmsBucketArn:
    Description: Arn of kms bucket for delayer tests automation
    Value: !Sub '${TestDelayerKmsBucket.Arn}'