AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

Resources:
  # PaperDeliveryDriverCapacities DynamoDB Table
    PaperDeliveryDriverCapacitiesTable:
      Type: AWS::DynamoDB::Table
      UpdateReplacePolicy: Retain
      DeletionPolicy: Retain
      Properties:
        TableName: !Sub '${ProjectName}-PaperDeliveryDriverCapacities'
        AttributeDefinitions:
          - AttributeName: "pk"
            AttributeType: "S"
          - AttributeName: "activationDateFrom"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "pk"
            KeyType: "HASH"
          - AttributeName: "activationDateFrom"
            KeyType: "RANGE"
        BillingMode: "PAY_PER_REQUEST"
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

Outputs:
  # Dynamo tables
    PaperDeliveryDriverCapacitiesDynamoTableName:
      Description: Name of dynamodb table containing capacities
      Value: !Ref PaperDeliveryDriverCapacitiesTable
    PaperDeliveryDriverCapacitiesDynamoTableArn:
      Description: ARN of dynamodb table containing capacities
      Value: !Sub '${PaperDeliveryDriverCapacitiesTable.Arn}'