AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  PnDelayerInputsRetentionHours:
    Type: Number
    Default: 168
    Description: Number of hours to retain data records in the stream

  PnDelayerInputsStandardAlarmThresholdsMs:
    Type: Number
    Default: 2000000
    Description: Threshold for standard alarms in milliseconds

  PnDelayerInputsnOnCallAlarmThresholdsMs:
    Type: Number
    Default: 2000000
    Description: Threshold for oncall alarms in milliseconds 

  AlarmSNSTopicArn:
    Type: String

Resources:
  # PaperDeliveryDriverCapacities DynamoDB Table
  PaperDeliveryDriverCapacitiesTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliveryDriverCapacities'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "activationDateFrom"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "activationDateFrom"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PaperDeliveryDriverCapacitiesDispatchedTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliveryDriverCapacitiesDispatched'
      AttributeDefinitions:
        - AttributeName: "deliveryDriverIdGeokey"
          AttributeType: "S"
        - AttributeName: "deliveryDate"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "deliveryDriverIdGeokey"
          KeyType: "HASH"
        - AttributeName: "deliveryDate"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PaperDeliveryHighPriorityTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliveryHighPriority'
      AttributeDefinitions:
        - AttributeName: "deliveryDriverIdGeokey"
          AttributeType: "S"
        - AttributeName: "createdAt"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "deliveryDriverIdGeokey"
          KeyType: "HASH"
        - AttributeName: "createdAt"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PaperDeliveryReadyToSendTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliveryReadyToSend'
      AttributeDefinitions:
        - AttributeName: "deliveryDate"
          AttributeType: "S"
        - AttributeName: "requestId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "deliveryDate"
          KeyType: "HASH"
        - AttributeName: "requestId"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  ### Kinesis Data Stream: CDC for PN-ACTION DynamoDB Table (INSERT CDC ARE THE INTERESTED ONE)
  PnDelayerInputsKinesisDataStream:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-data-stream.yaml"
      Parameters:
        StreamName: "pn-delayer_inputs"
        # PROVISIONED MODE: follow shard configuration
        StreamRetentionHours: !Ref PnDelayerInputsRetentionHours
        RequireManagedKey: true
        # USES SNSTopic used for all Kinesis alarms
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        StandardAlarmThresholdsMs: !Ref PnDelayerInputsStandardAlarmThresholdsMs
        OnCallAlarmThresholdsMs: !Ref PnDelayerInputsnOnCallAlarmThresholdsMs

Outputs:
  # Dynamo tables
  PaperDeliveryDriverCapacitiesTableName:
    Description: Name of dynamodb table containing capacities
    Value: !Ref PaperDeliveryDriverCapacitiesTable
  PaperDeliveryDriverCapacitiesTableArn:
    Description: ARN of dynamodb table containing capacities
    Value: !Sub '${PaperDeliveryDriverCapacitiesTable.Arn}'

  PaperDeliveryDriverCapacitiesDispatchedTableName:
    Description: Name of dynamodb table containing dispatched capacities
    Value: !Ref PaperDeliveryDriverCapacitiesDispatchedTable
  PaperDeliveryDriverCapacitiesDispatchedTableArn:
    Description: ARN of dynamodb table containing dispatched capacities
    Value: !Sub '${PaperDeliveryDriverCapacitiesDispatchedTable.Arn}'

  PaperDeliveryHighPriorityTableName:
    Description: Name of dynamodb table containing HighPriority paper deliveries
    Value: !Ref PaperDeliveryHighPriorityTable
  PaperDeliveryHighPriorityTableArn:
    Description: ARN of dynamodb table containing HighPriority paper deliveries
    Value: !Sub '${PaperDeliveryHighPriorityTable.Arn}'

  PaperDeliveryReadyToSendTableName:
    Description: Name of dynamodb table containing ReadyToSend paper deliveries
    Value: !Ref PaperDeliveryReadyToSendTable
  PaperDeliveryReadyToSendTableArn:
    Description: ARN of dynamodb table containing ReadyToSend paper deliveries
    Value: !Sub '${PaperDeliveryReadyToSendTable.Arn}'

  PnDelayerInputsKinesisDataStreamArn:
    Value: !GetAtt PnDelayerInputsKinesisDataStream.Outputs.KinesisStreamArn
    Description: "Kinesis source stream ARN"

  PnDelayerInputsKinesisDataStreamKMSArn:
    Value: !GetAtt PnDelayerInputsKinesisDataStream.Outputs.KinesisStreamKeyArn
    Description: "Kinesis source stream KMS ARN"