AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

Resources:
  # PaperDeliveryDriverCapacities DynamoDB Table
  PaperDeliveryDriverCapacitiesTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliveryDriverCapacities'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "activationDateFrom"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "activationDateFrom"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PaperDeliveryDriverUsedCapacitiesTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliveryDriverUsedCapacities'
      AttributeDefinitions:
        - AttributeName: "unifiedDeliveryDriverGeokey"
          AttributeType: "S"
        - AttributeName: "deliveryDate"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "unifiedDeliveryDriverGeokey"
          KeyType: "HASH"
        - AttributeName: "deliveryDate"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PaperDeliveryHighPriorityTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliveryHighPriority'
      AttributeDefinitions:
        - AttributeName: "unifiedDeliveryDriverGeokey"
          AttributeType: "S"
        - AttributeName: "createdAt"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "unifiedDeliveryDriverGeokey"
          KeyType: "HASH"
        - AttributeName: "createdAt"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PaperDeliveryReadyToSendTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperDeliveryReadyToSend'
      AttributeDefinitions:
        - AttributeName: "deliveryDate"
          AttributeType: "S"
        - AttributeName: "requestId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "deliveryDate"
          KeyType: "HASH"
        - AttributeName: "requestId"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

Outputs:
  # Dynamo tables
  PaperDeliveryDriverCapacitiesTableName:
    Description: Name of dynamodb table containing capacities
    Value: !Ref PaperDeliveryDriverCapacitiesTable
  PaperDeliveryDriverCapacitiesTableArn:
    Description: ARN of dynamodb table containing capacities
    Value: !Sub '${PaperDeliveryDriverCapacitiesTable.Arn}'

  PaperDeliveryDriverUsedCapacitiesTableName:
    Description: Name of dynamodb table containing used capacities
    Value: !Ref PaperDeliveryDriverUsedCapacitiesTable
  PaperDeliveryDriverUsedCapacitiesTableArn:
    Description: ARN of dynamodb table containing used capacities
    Value: !Sub '${PaperDeliveryDriverUsedCapacitiesTable.Arn}'

  PaperDeliveryHighPriorityTableName:
    Description: Name of dynamodb table containing HighPriority paper deliveries
    Value: !Ref PaperDeliveryHighPriorityTable
  PaperDeliveryHighPriorityTableArn:
    Description: ARN of dynamodb table containing HighPriority paper deliveries
    Value: !Sub '${PaperDeliveryHighPriorityTable.Arn}'

  PaperDeliveryReadyToSendTableName:
    Description: Name of dynamodb table containing ReadyToSend paper deliveries
    Value: !Ref PaperDeliveryReadyToSendTable
  PaperDeliveryReadyToSendTableArn:
    Description: ARN of dynamodb table containing ReadyToSend paper deliveries
    Value: !Sub '${PaperDeliveryReadyToSendTable.Arn}'